
version: '2.1'
services:
  webdav:
    extends:
      file: docker-compose-base.yml
      service: base-webdav
    networks:
      local-network:
        ipv4_address: ${IPV4_ADDRESS:-172.16.238.198}
        #ipv6_address: ${IPV6_ADDRESS:-2001:3984:3989::198}
    ports:
      - "${EXTERNAL_WEBDAV_80_PORT:-80}:80"
    restart: always
    volumes:
      - dav:/var/lib/dav

networks:
  local-network:
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
      #- subnet: 2001:3984:3989::/64

volumes:
  dav:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/dav
      o: bind
