
version: '3'
services:
  webdav:
    image: ${IMAGE_PREFIX:-bytemark/}${IMAGE_NAME:-webdav}:${IMAGE_TAG:-2.4}
    restart: always
    ports:
      - "${EXTERNAL_WEBDAV_80_PORT:-80}:80"
    environment:
      AUTH_TYPE: ${WEBDAV_AUTH_TYPE:-Basic}
      USERNAME: ${WEBDAV_USERNAME:-user}
      PASSWORD: ${WEBDAV_PASSWORD:-user_pass}
    volumes:
      - dav:/var/lib/dav

volumes:
  dav:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/dav
      o: bind
